export interface CatalogProduct {
  id: string;
  slug: string;
  categoryId: string;
  nameEn: string;
  nameAr: string;
  descriptionEn: string;
  descriptionAr: string;
  applicationsEn?: readonly string[];
  applicationsAr?: readonly string[];
  types?: readonly string[];
}

const product = (item: CatalogProduct) => item;

/**
 * Canonical public catalog, transcribed from the approved Arzana Arabia
 * descriptions and company profile. This is also used by quote validation.
 */
export const catalogProducts = [
  product({ id: 'p1', slug: 'ring-main-unit-rmu', categoryId: 'cat-1', nameEn: 'Ring Main Unit (RMU)', nameAr: 'وحدة الحلقة الرئيسية (RMU)', descriptionEn: 'Reliable medium-voltage switchgear designed for safe, efficient, and uninterrupted power distribution in utility and industrial networks.', descriptionAr: 'معدات مفاتيح جهد متوسط موثوقة مصممة لتوزيع الطاقة بأمان وكفاءة واستمرارية في شبكات المرافق والصناعة.', applicationsEn: ['Saudi Electricity Company (SEC)', 'National Grid', 'Industrial Plants', 'Commercial Buildings', 'Infrastructure Projects'], applicationsAr: ['الشركة السعودية للكهرباء (SEC)', 'الشبكة الوطنية', 'المنشآت الصناعية', 'المباني التجارية', 'مشاريع البنية التحتية'] }),
  product({ id: 'p2', slug: 'metering-rmu', categoryId: 'cat-1', nameEn: 'Metering RMU', nameAr: 'وحدة RMU للقياس', descriptionEn: 'Compact RMU with integrated metering for accurate energy measurement and reliable network monitoring.', descriptionAr: 'وحدة RMU مدمجة مزودة بقياس متكامل لقياس الطاقة بدقة ومراقبة الشبكة بموثوقية.' }),
  product({ id: 'p3', slug: 'oil-distribution-transformer', categoryId: 'cat-1', nameEn: 'Oil Distribution Transformer', nameAr: 'محول توزيع زيتي', descriptionEn: 'High-efficiency oil-immersed transformers delivering dependable power distribution with long service life.', descriptionAr: 'محولات مغمورة بالزيت عالية الكفاءة توفر توزيع طاقة موثوقاً بعمر خدمة طويل.' }),
  product({ id: 'p4', slug: 'dry-type-transformer', categoryId: 'cat-1', nameEn: 'Dry Type Transformer', nameAr: 'محول جاف', descriptionEn: 'Cast Resin Dry Type Transformers designed for commercial, industrial, healthcare, and utility applications. Fire-safe, environmentally friendly, and suitable for indoor installations requiring high reliability and low maintenance.', descriptionAr: 'محولات جافة من راتنج مصبوب مصممة للتطبيقات التجارية والصناعية والرعاية الصحية والمرافق، وآمنة من الحريق وصديقة للبيئة ومناسبة للتركيبات الداخلية التي تتطلب موثوقية عالية وصيانة منخفضة.', applicationsEn: ['Commercial Buildings', 'Hospitals', 'Data Centers', 'Industrial Facilities', 'Utility Substations'], applicationsAr: ['المباني التجارية', 'المستشفيات', 'مراكز البيانات', 'المنشآت الصناعية', 'محطات المرافق الفرعية'] }),
  product({ id: 'p5', slug: 'auto-isolation-transformer', categoryId: 'cat-1', nameEn: 'Auto / Isolation Transformer', nameAr: 'محول ذاتي / محول عزل', descriptionEn: 'Provides voltage conversion and electrical isolation for enhanced equipment protection and operational safety.', descriptionAr: 'يوفر تحويل الجهد والعزل الكهربائي لتعزيز حماية المعدات وسلامة التشغيل.' }),
  product({ id: 'p6', slug: 'automatic-transfer-switch-ats', categoryId: 'cat-1', nameEn: 'Automatic Transfer Switch (ATS)', nameAr: 'مفتاح تحويل تلقائي (ATS)', descriptionEn: 'Ensures uninterrupted power by automatically transferring loads between utility and backup power sources.', descriptionAr: 'يضمن استمرارية الطاقة عبر تحويل الأحمال تلقائياً بين مصادر طاقة المرفق والطاقة الاحتياطية.' }),
  product({ id: 'p7', slug: 'disconnect-switch', categoryId: 'cat-1', nameEn: 'Disconnect Switch', nameAr: 'مفتاح فصل', descriptionEn: 'Provides safe electrical isolation for maintenance and protection of electrical systems.', descriptionAr: 'يوفر عزلاً كهربائياً آمناً لصيانة الأنظمة الكهربائية وحمايتها.' }),
  product({ id: 'p8', slug: 'power-factor-correction-pfc', categoryId: 'cat-1', nameEn: 'Power Factor Correction (PFC)', nameAr: 'تصحيح معامل القدرة (PFC)', descriptionEn: 'Improves energy efficiency, reduces power losses, and minimizes electricity costs.', descriptionAr: 'يحسن كفاءة الطاقة ويقلل فاقد القدرة وتكاليف الكهرباء.' }),
  product({ id: 'p9', slug: 'low-voltage-switchboard', categoryId: 'cat-1', nameEn: 'Low Voltage Switchboard', nameAr: 'لوحة مفاتيح الجهد المنخفض', descriptionEn: 'Custom-built LV switchboards engineered for reliable power distribution and protection.', descriptionAr: 'لوحات جهد منخفض مصممة حسب الطلب لتوزيع الطاقة والحماية بموثوقية.' }),
  product({ id: 'p10', slug: 'uninterruptible-power-supply-ups', categoryId: 'cat-2', nameEn: 'Uninterruptible Power Supply (UPS)', nameAr: 'مزود طاقة غير منقطع (UPS)', descriptionEn: 'Reliable backup power solutions available in Line Interactive, Online, and Modular configurations.', descriptionAr: 'حلول طاقة احتياطية موثوقة متاحة بتكوينات Line Interactive وOnline وModular.', types: ['Line Interactive', 'Online', 'Modular'] }),
  product({ id: 'p11', slug: 'static-transfer-switch-sts', categoryId: 'cat-2', nameEn: 'Static Transfer Switch (STS)', nameAr: 'مفتاح تحويل ثابت (STS)', descriptionEn: 'Ultra-fast power source switching to ensure continuous operation of critical loads.', descriptionAr: 'تحويل فائق السرعة لمصادر الطاقة لضمان التشغيل المستمر للأحمال الحرجة.' }),
  product({ id: 'p12', slug: 'static-voltage-regulator-svr', categoryId: 'cat-2', nameEn: 'Static Voltage Regulator (SVR)', nameAr: 'منظم جهد ثابت (SVR)', descriptionEn: 'Maintains stable output voltage to protect sensitive electrical equipment.', descriptionAr: 'يحافظ على جهد خرج مستقر لحماية المعدات الكهربائية الحساسة.' }),
  product({ id: 'p13', slug: 'automatic-voltage-regulator-avr', categoryId: 'cat-2', nameEn: 'Automatic Voltage Regulator (AVR)', nameAr: 'منظم جهد تلقائي (AVR)', descriptionEn: 'Automatically corrects voltage fluctuations for improved equipment performance.', descriptionAr: 'يصحح تقلبات الجهد تلقائياً لتحسين أداء المعدات.' }),
  product({ id: 'p14', slug: 'frequency-converter', categoryId: 'cat-2', nameEn: 'Frequency Converter', nameAr: 'محول تردد', descriptionEn: 'Converts electrical frequency between 50Hz, 60Hz, and 400Hz for specialized applications.', descriptionAr: 'يحول التردد الكهربائي بين 50Hz و60Hz و400Hz للتطبيقات المتخصصة.', types: ['50Hz', '60Hz', '400Hz'] }),
  product({ id: 'p15', slug: 'battery-charger', categoryId: 'cat-2', nameEn: 'Battery Charger', nameAr: 'شاحن بطاريات', descriptionEn: 'Industrial battery chargers designed for reliable charging and continuous DC power applications.', descriptionAr: 'شواحن بطاريات صناعية مصممة للشحن الموثوق وتطبيقات طاقة التيار المستمر المستمرة.' }),
  product({ id: 'p16', slug: 'safety-nets', categoryId: 'cat-3', nameEn: 'Safety Nets', nameAr: 'شبكات السلامة', descriptionEn: 'Engineered fall protection net systems designed to protect personnel and materials on construction sites. Manufactured to meet international safety standards for reliable performance.', descriptionAr: 'أنظمة شبكات حماية من السقوط مصممة لحماية الأفراد والمواد في مواقع البناء، ومصنعة وفق معايير السلامة الدولية لأداء موثوق.' }),
  product({ id: 'p17', slug: 'edge-protection-systems', categoryId: 'cat-3', nameEn: 'Edge Protection Systems', nameAr: 'أنظمة حماية الحواف', descriptionEn: 'Temporary edge protection solutions that provide safe working environments on rooftops, floor slabs, and elevated structures, reducing the risk of falls during construction.', descriptionAr: 'حلول مؤقتة لحماية الحواف توفر بيئات عمل آمنة على الأسطح وبلاطات الأرضيات والمنشآت المرتفعة، وتقلل مخاطر السقوط أثناء الإنشاء.' }),
  product({ id: 'p18', slug: 'loading-platforms', categoryId: 'cat-3', nameEn: 'Loading Platforms', nameAr: 'منصات التحميل', descriptionEn: 'Heavy-duty loading platforms designed for the safe handling and transfer of construction materials between floors, improving site efficiency and worker safety.', descriptionAr: 'منصات تحميل شديدة التحمل مصممة للمناولة والنقل الآمن لمواد البناء بين الطوابق، بما يحسن كفاءة الموقع وسلامة العاملين.' }),
  product({ id: 'p19', slug: 'shaft-gates', categoryId: 'cat-3', nameEn: 'Shaft Gates', nameAr: 'بوابات المناور', descriptionEn: 'Robust temporary safety gates for elevator and service shafts, preventing unauthorized access and protecting workers from fall hazards while maintaining easy access for authorized personnel.', descriptionAr: 'بوابات سلامة مؤقتة متينة لمناور المصاعد والخدمات تمنع الدخول غير المصرح به وتحمي العاملين من مخاطر السقوط مع الحفاظ على سهولة الوصول للمصرح لهم.' }),
  product({ id: 'p20', slug: 'ni-cd-batteries', categoryId: 'cat-4', nameEn: 'Ni-Cd Batteries', nameAr: 'بطاريات النيكل والكادميوم', descriptionEn: 'Long-life nickel-cadmium batteries designed for demanding industrial applications.', descriptionAr: 'بطاريات نيكل وكادميوم طويلة العمر مصممة للتطبيقات الصناعية الشاقة.' }),
  product({ id: 'p21', slug: 'lead-acid-batteries', categoryId: 'cat-4', nameEn: 'Lead Acid Batteries', nameAr: 'بطاريات الرصاص الحمضية', descriptionEn: 'Reliable AGM, GEL, and Flooded batteries for backup power and energy storage.', descriptionAr: 'بطاريات AGM وGEL والبطاريات المغمورة الموثوقة للطاقة الاحتياطية وتخزين الطاقة.', types: ['AGM', 'GEL', 'Flooded'] }),
  product({ id: 'p22', slug: 'opzs-batteries', categoryId: 'cat-4', nameEn: 'OPzS Batteries', nameAr: 'بطاريات OPzS', descriptionEn: 'High-performance tubular batteries offering exceptional durability and long service life.', descriptionAr: 'بطاريات أنبوبية عالية الأداء توفر متانة استثنائية وعمر خدمة طويل.' }),
  product({ id: 'p23', slug: 'lithium-batteries', categoryId: 'cat-4', nameEn: 'Lithium Batteries', nameAr: 'بطاريات الليثيوم', descriptionEn: 'Modern lithium battery systems providing high energy density and fast charging performance.', descriptionAr: 'أنظمة بطاريات ليثيوم حديثة توفر كثافة طاقة عالية وأداء شحن سريع.' }),
  product({ id: 'p24', slug: 'multifunction-power-meter', categoryId: 'cat-5', nameEn: 'Multifunction Power Meter', nameAr: 'مقياس طاقة متعدد الوظائف', descriptionEn: 'Advanced meters for monitoring voltage, current, power, energy, and electrical parameters.', descriptionAr: 'عدادات متقدمة لمراقبة الجهد والتيار والقدرة والطاقة والمعلمات الكهربائية.' }),
  product({ id: 'p25', slug: 'digital-multimeter', categoryId: 'cat-5', nameEn: 'Digital Multimeter', nameAr: 'جهاز قياس متعدد رقمي', descriptionEn: 'Professional instruments for accurate electrical testing and troubleshooting.', descriptionAr: 'أجهزة احترافية للاختبار الكهربائي الدقيق واستكشاف الأعطال.' }),
  product({ id: 'p26', slug: 'digital-analog-panel-meters', categoryId: 'cat-5', nameEn: 'Digital & Analog Panel Meters', nameAr: 'مقاييس لوحات رقمية وتناظرية', descriptionEn: 'Reliable panel-mounted meters for continuous electrical monitoring.', descriptionAr: 'مقاييس موثوقة تثبت على اللوحات للمراقبة الكهربائية المستمرة.' }),
  product({ id: 'p27', slug: 'energy-meter-kwh', categoryId: 'cat-5', nameEn: 'Energy Meter (kWh)', nameAr: 'مقياس طاقة (kWh)', descriptionEn: 'Accurate energy measurement for commercial and industrial installations.', descriptionAr: 'قياس دقيق للطاقة للتركيبات التجارية والصناعية.' }),
  product({ id: 'p28', slug: 'current-transformer-ct', categoryId: 'cat-5', nameEn: 'Current Transformer (CT)', nameAr: 'محول تيار (CT)', descriptionEn: 'Precision current measurement devices for metering and protection systems.', descriptionAr: 'أجهزة قياس تيار دقيقة لأنظمة القياس والحماية.' }),
  product({ id: 'p29', slug: 'protection-relay', categoryId: 'cat-5', nameEn: 'Protection Relay', nameAr: 'مرحل حماية', descriptionEn: 'Intelligent protection relays ensuring fast fault detection and reliable network protection.', descriptionAr: 'مرحلات حماية ذكية تضمن اكتشاف الأعطال بسرعة وحماية موثوقة للشبكة.' }),
  product({ id: 'p30', slug: 'transducers-isolators', categoryId: 'cat-5', nameEn: 'Transducers & Isolators', nameAr: 'محولات إشارة وعوازل', descriptionEn: 'Signal conversion and isolation solutions for industrial automation systems.', descriptionAr: 'حلول لتحويل الإشارات وعزلها لأنظمة الأتمتة الصناعية.' }),
  product({ id: 'p31', slug: 'temperature-controller', categoryId: 'cat-5', nameEn: 'Temperature Controller', nameAr: 'متحكم درجة الحرارة', descriptionEn: 'Precise temperature monitoring and control for industrial processes.', descriptionAr: 'مراقبة وتحكم دقيقان بدرجة الحرارة للعمليات الصناعية.' }),
  product({ id: 'p32', slug: 'converters-recorders', categoryId: 'cat-5', nameEn: 'Converters & Recorders', nameAr: 'محولات ومسجلات', descriptionEn: 'Industrial devices for signal conversion, monitoring, and data recording.', descriptionAr: 'أجهزة صناعية لتحويل الإشارات والمراقبة وتسجيل البيانات.' }),
  product({ id: 'p33', slug: 'telecommunication-shelter', categoryId: 'cat-6', nameEn: 'Telecommunication Shelter', nameAr: 'مأوى اتصالات', descriptionEn: 'Factory-built telecommunication shelters designed to withstand the harsh climatic conditions of Saudi Arabia. Complete with thermal insulation, HVAC systems, electrical distribution, fire protection, lighting, and equipment racks.', descriptionAr: 'مآوي اتصالات مصنّعة في المصنع ومصممة لتحمل الظروف المناخية القاسية في المملكة العربية السعودية، ومكتملة بالعزل الحراري وأنظمة التكييف وتوزيع الكهرباء والحماية من الحريق والإضاءة ورفوف المعدات.', applicationsEn: ['Telecom Networks', 'Fiber Optic Sites', '5G Infrastructure', 'Remote Communication Stations'], applicationsAr: ['شبكات الاتصالات', 'مواقع الألياف الضوئية', 'بنية 5G', 'محطات الاتصالات النائية'] }),
  product({ id: 'p34', slug: 'lcc-container', categoryId: 'cat-6', nameEn: 'LCC Container', nameAr: 'حاوية مركز التحكم المحلي (LCC)', descriptionEn: 'Prefabricated Local Control Center (LCC) containers engineered for electrical substations, renewable energy, water treatment, and industrial facilities. Delivered as complete plug-and-play control buildings with HVAC, lighting, fire protection, UPS, and control panels.', descriptionAr: 'حاويات مركز التحكم المحلي (LCC) مسبقة الصنع ومصممة للمحطات الكهربائية والطاقة المتجددة ومعالجة المياه والمنشآت الصناعية، وتورد كمبان تحكم متكاملة جاهزة للتشغيل مزودة بالتكييف والإضاءة والحماية من الحريق وUPS ولوحات التحكم.', applicationsEn: ['SEC Substations', 'Saudi Aramco', 'SWCC', 'Water Treatment Plants', 'Renewable Energy Projects'], applicationsAr: ['محطات SEC الفرعية', 'أرامكو السعودية', 'SWCC', 'محطات معالجة المياه', 'مشاريع الطاقة المتجددة'] }),
  product({ id: 'p35', slug: 'electrical-house-e-house', categoryId: 'cat-6', nameEn: 'Electrical House (E-House)', nameAr: 'المبنى الكهربائي (E-House)', descriptionEn: 'Custom-built prefabricated Electrical Houses integrating MV/LV switchgear, protection systems, UPS, batteries, HVAC, and SCADA equipment into a factory-tested modular building for rapid site installation.', descriptionAr: 'مبان كهربائية مسبقة الصنع ومصممة حسب الطلب تدمج معدات مفاتيح MV/LV وأنظمة الحماية وUPS والبطاريات والتكييف ومعدات SCADA في مبنى معياري مختبر في المصنع للتركيب السريع في الموقع.' }),
  product({ id: 'p36', slug: 'data-center-cabinets', categoryId: 'cat-7', nameEn: 'Data Center Cabinets', nameAr: 'خزائن مراكز البيانات', descriptionEn: 'Robust server cabinets designed for secure and efficient IT infrastructure.', descriptionAr: 'خزائن خوادم متينة مصممة لبنية تقنية معلومات آمنة وفعالة.' }),
  product({ id: 'p37', slug: 'battery-cabinets', categoryId: 'cat-7', nameEn: 'Battery Cabinets', nameAr: 'خزائن البطاريات', descriptionEn: 'Safe and organized battery enclosures for UPS and DC power systems.', descriptionAr: 'حاويات بطاريات آمنة ومنظمة لأنظمة UPS وطاقة التيار المستمر.' }),
  product({ id: 'p38', slug: 'battery-racks', categoryId: 'cat-7', nameEn: 'Battery Racks', nameAr: 'رفوف البطاريات', descriptionEn: 'Heavy-duty battery support systems engineered for industrial applications.', descriptionAr: 'أنظمة دعم بطاريات شديدة التحمل مصممة للتطبيقات الصناعية.' }),
  product({ id: 'p39', slug: 'fire-alarm-system', categoryId: 'cat-8', nameEn: 'Fire Alarm System', nameAr: 'نظام إنذار الحريق', descriptionEn: 'Advanced fire detection systems providing early warning and enhanced safety.', descriptionAr: 'أنظمة كشف حريق متقدمة توفر إنذاراً مبكراً وتعزز السلامة.' }),
  product({ id: 'p40', slug: 'fire-fighting-system', categoryId: 'cat-8', nameEn: 'Fire Fighting System', nameAr: 'نظام مكافحة الحريق', descriptionEn: 'Integrated fire suppression solutions protecting personnel and critical assets.', descriptionAr: 'حلول متكاملة لإخماد الحريق تحمي الأفراد والأصول الحرجة.' }),
  product({ id: 'p41', slug: 'fire-extinguisher', categoryId: 'cat-8', nameEn: 'Fire Extinguisher', nameAr: 'طفاية حريق', descriptionEn: 'Certified portable extinguishers suitable for industrial and commercial facilities.', descriptionAr: 'طفايات محمولة معتمدة ومناسبة للمنشآت الصناعية والتجارية.' }),
  product({ id: 'p42', slug: 'led-obstruction-light', categoryId: 'cat-8', nameEn: 'LED Obstruction Light', nameAr: 'ضوء عوائق LED', descriptionEn: 'High-visibility aviation obstruction lighting for towers and tall structures.', descriptionAr: 'إضاءة عوائق للطيران عالية الوضوح للأبراج والمنشآت العالية.' }),
] as const satisfies readonly CatalogProduct[];

export type CatalogProductId = (typeof catalogProducts)[number]['id'];

export const catalogProductById = new Map(
  catalogProducts.map((catalogProduct) => [catalogProduct.id, catalogProduct] as const),
);

export function findCatalogProduct(productId: string): CatalogProduct | undefined {
  return catalogProductById.get(productId);
}
